import Navbar from '@/components/Navbar';
import Head from 'next/head'
import Image from 'next/image'
import ArticleImage from '../images/article.jpg'
import api, { Article, Tag }  from '../mock/api'
import { GetStaticProps } from 'next';




export default function Home({articles} : {articles : Article[]})  {
  
  
    const tags:string[] = [];
    articles.forEach((item) => {
      item.taxonomy.tags.forEach((tag) => {
        if (!tags.includes(tag.text)) {
          tags.push(tag.text);
        }
      });
    });
    console.log(tags);
    






  return (
    <>
      <Head>
        <title>La Nación Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <Navbar/>
        <main className='z-[-1] relative' >
          <div className='bg-gray-200 h-44 w-full'>
            <div className=' bg-blue-300 h-full max-w-[1280px] mx-auto'></div>
          </div>
          <section className='grid grid-cols-[1fr_280px] max-w-[1280px] mx-auto mt-12'>
            <div className='mr-20'>
              <h1 className='underline text-4xl'>Acumulado Grilla</h1>
              <div className='mt-4 mb-6 flex items-center gap-2'>
                <span>Platos principales</span> 
                <span className="font-bold text-2xl">·</span> 
                <span>Cerdo</span> 
                <span className="font-bold text-2xl">·</span> 
                <span>Papas</span> 
                <span className="font-bold text-2xl">·</span> 
                <span>Date un gustito</span> 
                <span className="font-bold text-2xl">·</span> 
                <span>La Familia</span>
              </div>
              <div className='grid grid-cols-3 gap-10 justify-between items-center'>
                <article className=''>
                  <Image src={ArticleImage} alt="Imagen Articulo"/>
                  <p><span className="font-bold">La escuela.</span> que tiene de escudo al Che Guevara y donde izan la bandera de Cuba</p>
                  <span className='text-[15px] text-gray-500'>1 de Julio de 2019</span>
                </article>
                <article className=''>
                  <Image src={ArticleImage} alt="Imagen Articulo"/>
                  <p><span className="font-bold">La escuela.</span> que tiene de escudo al Che Guevara y donde izan la bandera de Cuba</p>
                  <span className='text-[15px] text-gray-500'>1 de Julio de 2019</span>
                </article>
                <article className=''>
                  <Image src={ArticleImage} alt="Imagen Articulo"/>
                  <p><span className="font-bold">La escuela.</span> que tiene de escudo al Che Guevara y donde izan la bandera de Cuba</p>
                  <span className='text-[15px] text-gray-500'>1 de Julio de 2019</span>
                </article>
                <article className=''>
                  <Image src={ArticleImage} alt="Imagen Articulo"/>
                  <p><span className="font-bold">La escuela.</span> que tiene de escudo al Che Guevara y donde izan la bandera de Cuba</p>
                  <span className='text-[15px] text-gray-500'>1 de Julio de 2019</span>
                </article>
                <article className=''>
                  <Image src={ArticleImage} alt="Imagen Articulo"/>
                  <p><span className="font-bold">La escuela.</span> que tiene de escudo al Che Guevara y donde izan la bandera de Cuba</p>
                  <span className='text-[15px] text-gray-500'>1 de Julio de 2019</span>
                </article>
                <article className=''>
                  <Image src={ArticleImage} alt="Imagen Articulo"/>
                  <p><span className="font-bold">La escuela.</span> que tiene de escudo al Che Guevara y donde izan la bandera de Cuba</p>
                  <span className='text-[15px] text-gray-500'>1 de Julio de 2019</span>
                </article>
                <article className=''>
                  <Image src={ArticleImage} alt="Imagen Articulo"/>
                  <p><span className="font-bold">La escuela.</span> que tiene de escudo al Che Guevara y donde izan la bandera de Cuba</p>
                  <span className='text-[15px] text-gray-500'>1 de Julio de 2019</span>
                </article>
                <article className=''>
                  <Image src={ArticleImage} alt="Imagen Articulo"/>
                  <p><span className="font-bold">La escuela.</span> que tiene de escudo al Che Guevara y donde izan la bandera de Cuba</p>
                  <span className='text-[15px] text-gray-500'>1 de Julio de 2019</span>
                </article>
              </div>
            </div>
            <div className='h-full bg-blue-300 '>
            </div>
          </section>
        </main>

    </>
  )
}
  

export const getStaticProps : GetStaticProps = async ( )=> {

  const articles = await api.list()
  return{
    props: {
      articles
    }
  }
}